### ISSUE TITLE
Implement OS menu bar

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon-desktop#23]
Right now the app uses the default menu bar for Electron and it's a bit sad :(.

**Comment by onbjerg** [comment]
This is only the case when doing `npm run` on macOS because it uses the pre-built Electron binary.

For builds (`bin/build`) there is no menu bar because of [this line](https://github.com/aragon/aragon-desktop/blob/master/src/main.js#L52). For Windows and Linux there is no menu bar in the window even when using `npm start` because of the same line.

**Comment by sohkai** [comment]
Closed by https://github.com/aragon/aragon-desktop/pull/68.
